### ISSUE TITLE
使用报错 path.replaceWith()

### ISSUE THREAD

**Issue by terrytan95** [yklydxtt/react-class-to-fc#2]
错误信息:
```
Error: You passed `path.replaceWith()` a falsy node, use `path.remove()` instead
    at NodePath.replaceWith (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/path/replacement.js:88:11)
    at MemberExpression (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/src/Transformer.js:97:37)
    at NodePath._call (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/context.js:99:16)
    at TraversalContext.visitSingle (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/context.js:73:19)
    at TraversalContext.visit (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/context.js:127:19)
    at Function.traverse.node (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/mtan/.nvm/versions/node/v12.14.1/lib/node_modules/react-class-to-fc/node_modules/@babel/traverse/lib/path/context.js:97:18)
```

**Comment by terrytan95** [comment]
应该不是啥大问题, 看看能改不

**Comment by yklydxtt** [comment]
> 应该不是啥大问题, 看看能改不

能把你要转化的那段react代码提供一下吗

**Comment by terrytan95** [comment]
抱歉，不行哦，是公司代码😂想试试看来着
